name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 设置完整的Android SDK环境，这将包含CMake
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: tools platform-tools platforms;android-28 build-tools;28.0.3 cmake;3.10.2.4988454
        cache: true

    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload arm64 artifacts
      id: upload-arm64-apk
      uses: actions/upload-artifact@v4
      with:
        name: release-arm64-apk
        path: app/build/outputs/apk/release/*arm64-v8a*.apk
      continue-on-error: true

    - name: Upload armv7 artifacts
      id: upload-armv7-apk
      uses: actions/upload-artifact@v4
      with:
        name: release-armv7-apk
        path: app/build/outputs/apk/release/*-v7a*.apk
      continue-on-error: true
